{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    }
   ],
   "source": [
    "# Run this app with `python app.py` and\n",
    "# visit http://127.0.0.1:8050/ in your web browser.\n",
    "\n",
    "from dash import Dash, html, dcc\n",
    "import plotly.express as px\n",
    "import pandas as pd\n",
    "\n",
    "app = Dash(__name__)\n",
    "\n",
    "colors = {\n",
    "    'background': '#111111',\n",
    "    'text': '#7FDBFF'\n",
    "}\n",
    "\n",
    "# assume you have a \"long-form\" data frame\n",
    "# see https://plotly.com/python/px-arguments/ for more options\n",
    "df = pd.DataFrame({\n",
    "    \"Fruit\": [\"Apples\", \"Oranges\", \"Bananas\", \"Apples\", \"Oranges\", \"Bananas\"],\n",
    "    \"Amount\": [4, 1, 2, 2, 4, 5],\n",
    "    \"City\": [\"SF\", \"SF\", \"SF\", \"Montreal\", \"Montreal\", \"Montreal\"]\n",
    "})\n",
    "\n",
    "fig = px.bar(df, x=\"Fruit\", y=\"Amount\", color=\"City\", barmode=\"group\")\n",
    "\n",
    "fig.update_layout(\n",
    "    plot_bgcolor=colors['background'],\n",
    "    paper_bgcolor=colors['background'],\n",
    "    font_color=colors['text']\n",
    ")\n",
    "\n",
    "app.layout = html.Div(style={'backgroundColor': colors['background']}, children=[\n",
    "    html.H1(\n",
    "        children='Hello Dash',\n",
    "        style={\n",
    "            'textAlign': 'center',\n",
    "            'color': colors['text']\n",
    "        }\n",
    "    ),\n",
    "\n",
    "    html.Div(children='Dash: A web application framework for your data.', style={\n",
    "        'textAlign': 'center',\n",
    "        'color': colors['text']\n",
    "    }),\n",
    "\n",
    "    dcc.Graph(\n",
    "        id='example-graph-2',\n",
    "        figure=fig\n",
    "    )\n",
    "])\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    }
   ],
   "source": [
    "from dash import Dash, html\n",
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv('https://gist.githubusercontent.com/chriddyp/c78bf172206ce24f77d6363a2d754b59/raw/c353e8ef842413cae56ae3920b8fd78468aa4cb2/usa-agricultural-exports-2011.csv')\n",
    "\n",
    "\n",
    "def generate_table(dataframe, max_rows=10):\n",
    "    return html.Table([\n",
    "        html.Thead(\n",
    "            html.Tr([html.Th(col) for col in dataframe.columns])\n",
    "        ),\n",
    "        html.Tbody([\n",
    "            html.Tr([\n",
    "                html.Td(dataframe.iloc[i][col]) for col in dataframe.columns\n",
    "            ]) for i in range(min(len(dataframe), max_rows))\n",
    "        ])\n",
    "    ])\n",
    "\n",
    "\n",
    "app = Dash(__name__)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H4(children='US Agriculture Exports (2011)'),\n",
    "    generate_table(df)\n",
    "])\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n"
     ]
    }
   ],
   "source": [
    "# Run this app with `python app.py` and\n",
    "# visit http://127.0.0.1:8050/ in your web browser.\n",
    "\n",
    "from dash import Dash, dcc, html\n",
    "import plotly.express as px\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "app = Dash(__name__)\n",
    "\n",
    "df = pd.read_csv('https://gist.githubusercontent.com/chriddyp/5d1ea79569ed194d432e56108a04d188/raw/a9f9e8076b837d541398e999dcbac2b2826a81f8/gdp-life-exp-2007.csv')\n",
    "\n",
    "fig = px.scatter(df, x=\"gdp per capita\", y=\"life expectancy\",\n",
    "                 size=\"population\", color=\"continent\", hover_name=\"country\",\n",
    "                 log_x=True, size_max=60)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    dcc.Graph(\n",
    "        id='life-exp-vs-gdp',\n",
    "        figure=fig\n",
    "    )\n",
    "])\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1402, in _setup_server\n",
      "    dev_tools = self._setup_dev_tools(\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 758, in _generate_scripts_html\n",
      "    scripts = self._generate_scripts_html()\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 704, in _collect_and_register_resources\n",
      "    x.get(\"http-equiv\", \"\") == \"X-UA-Compatible\" for x in meta_tags\n",
      "  File \"/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 680, in _relative_url_path\n",
      "    [\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizabethjohnson/opt/anaconda3/lib/python3.9/site-packages/dash/deps/polyfill@7.12.1.min.js'\n"
     ]
    }
   ],
   "source": [
    "# Run this app with `python app.py` and\n",
    "# visit http://127.0.0.1:8050/ in your web browser.\n",
    "\n",
    "from dash import Dash, dcc, html\n",
    "import plotly.express as px\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "app = Dash(__name__)\n",
    "\n",
    "df = pd.read_csv('https://gist.githubusercontent.com/chriddyp/5d1ea79569ed194d432e56108a04d188/raw/a9f9e8076b837d541398e999dcbac2b2826a81f8/gdp-life-exp-2007.csv')\n",
    "\n",
    "fig = px.scatter(df, x=\"gdp per capita\", y=\"life expectancy\",\n",
    "                 size=\"population\", color=\"continent\", hover_name=\"country\",\n",
    "                 log_x=True, size_max=60)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    dcc.Graph(\n",
    "        id='life-exp-vs-gdp',\n",
    "        figure=fig\n",
    "    )\n",
    "])\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "ce9cee3d5ee3f2a4e0552862d2333eeebf09f6e5235c1f229d60a7fc27105b3c"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
